using Catglobe.CgScript.EditorSupport.Parsing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Catglobe.CgScript.EditorSupport.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator.
/// For each <c>.cgs</c> file included as an <c>AdditionalFile</c> in the consuming project,
/// detects the workflow parameter pattern and emits a typed C# wrapper method inside
/// <c>CgScriptWrappers</c> (a <c>partial static class</c> the user must declare in their project).
/// Also runs the CgScript semantic analyser and reports any diagnostics as build warnings/errors.
///
/// Usage in consuming .csproj:
/// <code>
///   &lt;ItemGroup&gt;
///     &lt;AdditionalFiles Include="CgScript\**\*.cgs" /&gt;
///   &lt;/ItemGroup&gt;
/// </code>
/// </summary>
[Generator]
public sealed class CgScriptWrapperGenerator : IIncrementalGenerator
{
   /// <summary>Full metadata name of the marker attribute we emit.</summary>
   private const string CgScriptSerializerAttributeName = "Catglobe.CgScript.CgScriptSerializerAttribute";

   public void Initialize(IncrementalGeneratorInitializationContext context)
   {
      // ── Emit CgScriptSerializerAttribute so consuming projects can reference it ──
      context.RegisterPostInitializationOutput(static ctx =>
         ctx.AddSource("CgScriptSerializerAttribute.g.cs", SourceText.From("""
            // <auto-generated />
            #nullable enable
            namespace Catglobe.CgScript
            {
                /// <summary>
                /// Marks a <see cref="global::System.Text.Json.Serialization.JsonSerializerContext"/> subclass
                /// as the AOT-safe JSON context for CgScript generated wrappers.
                /// Exactly one class in the assembly must carry this attribute.
                /// The class must also declare <c>[JsonSerializable(typeof(ReturnType))]</c> for every
                /// non-primitive return type used by scripts in this project.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed class CgScriptSerializerAttribute : global::System.Attribute { }
            }
            """, Encoding.UTF8)));

      // ── Collect all .cgs AdditionalFiles ─────────────────────────────────────
      var cgsFiles = context.AdditionalTextsProvider
         .Where(static f => f.Path.EndsWith(".cgs", System.StringComparison.OrdinalIgnoreCase));

      // ── Collect classes bearing [CgScriptSerializer] ──────────────────────────
      // For each such class, record its fully-qualified name and the set of
      // type-names passed to [JsonSerializable(...)] attributes declared on it.
      var serializerClasses = context.SyntaxProvider
         .CreateSyntaxProvider(
            predicate: static (node, _) =>
               node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0,
            transform: static (ctx, _) =>
            {
               var cls    = (ClassDeclarationSyntax)ctx.Node;
               var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls);
               if (symbol is null) return default;

               bool hasCgScriptSerializer = symbol.GetAttributes().Any(
                  a => a.AttributeClass?.ToDisplayString() == CgScriptSerializerAttributeName);
               if (!hasCgScriptSerializer) return default;

               var ns       = symbol.ContainingNamespace?.IsGlobalNamespace == false
                  ? symbol.ContainingNamespace.ToDisplayString()
                  : null;
               var fullName = ns is null ? symbol.Name : $"{ns}.{symbol.Name}";

               var registered = ImmutableHashSet.CreateBuilder<string>(System.StringComparer.Ordinal);
               foreach (var attr in symbol.GetAttributes())
               {
                  if (attr.AttributeClass?.Name != "JsonSerializableAttribute") continue;
                  if (attr.ConstructorArguments.Length == 0) continue;
                  if (attr.ConstructorArguments[0].Value is ITypeSymbol ts)
                  {
                     var fullName2 = ts.ToDisplayString();
                     registered.Add(fullName2);
                     // Also add the unqualified simple name so @return/@param annotations
                     // without a namespace prefix (e.g. "TagSummary") match correctly.
                     var simpleName = GetSimpleName(fullName2);
                     if (simpleName != fullName2)
                        registered.Add(simpleName);
                  }
               }

               return (IsValid: true, FullName: fullName, Registered: (ImmutableHashSet<string>)registered.ToImmutable());
            })
         .Where(static x => x.IsValid)
         .Collect();

      // ── Combine everything: per-file × compilation × context classes ──────────
      var combined = cgsFiles
         .Combine(context.CompilationProvider)
         .Combine(serializerClasses);

      context.RegisterSourceOutput(combined, static (spc, pair) =>
      {
         var ((file, compilation), ctxClasses) = pair;
         var text = file.GetText(spc.CancellationToken);
         if (text is null) return;

         var source     = text.ToString();
         var baseName   = Path.GetFileNameWithoutExtension(file.Path);
         var hintName   = SanitizeHintName(baseName);
         // Strip deployer metadata (@NNN[.public]) — same convention as ScriptFromFileOnDisk
         var scriptName = s_deployerSuffix.Replace(baseName, string.Empty);

         // ── CgScript semantic diagnostics ─────────────────────────────────────
         ReportSemanticDiagnostics(spc, file, text, source);

         // ── Validate [CgScriptSerializer] context ─────────────────────────────
         if (ctxClasses.Length == 0)
         {
            spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
               CgScriptDiagnostics.MissingCgScriptSerializer,
               Location.None,
               "None found — add [CgScriptSerializer] to a partial JsonSerializerContext class."));
            return;
         }
         if (ctxClasses.Length > 1)
         {
            spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
               CgScriptDiagnostics.MissingCgScriptSerializer,
               Location.None,
               $"Found {ctxClasses.Length}: {string.Join(", ", ctxClasses.Select(c => c.FullName))} — only one is allowed."));
            return;
         }

         var serCtx = ctxClasses[0];

         // ── Wrapper code generation ───────────────────────────────────────────
         var (meta, missingAnnotations) = ScriptParser.TryParse(scriptName, source);
         foreach (var (paramName, csType) in missingAnnotations)
         {
            spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
               CgScriptDiagnostics.MissingParamAnnotation,
               Location.None,
               paramName, csType));
         }
         if (meta is null) return;

         // ── CGS011: check [JsonSerializable] for non-primitive return + param types ──
         // Map void→object (WrapperEmitter uses object as the return type for void scripts)
         var csReturnType = meta.ReturnType == "void" ? "object" : meta.ReturnType;
         if (NeedsJsonSerializableCheck(csReturnType) &&
             !serCtx.Registered.Contains(csReturnType))
         {
            spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
               CgScriptDiagnostics.MissingJsonSerializable,
               Location.None,
               csReturnType, meta.ScriptName));
            return;
         }

         foreach (var p in meta.Parameters)
         {
            if (NeedsJsonSerializableCheck(p.CsType) &&
                !serCtx.Registered.Contains(p.CsType))
            {
               spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
                  CgScriptDiagnostics.MissingJsonSerializable,
                  Location.None,
                  p.CsType, meta.ScriptName));
               return;
            }
         }

         var ns         = compilation.AssemblyName ?? "CgScriptGenerated";
         var body       = WrapperEmitter.Emit(meta, ns, serCtx.FullName);
         var fullSource = WrapperEmitter.WrapInPartialClass(ns, body);

         spc.AddSource($"CgScript.{hintName}.g.cs",
            SourceText.From(fullSource, Encoding.UTF8));
      });
   }

   /// <summary>Strips deployer metadata (@NNN[.public]) from a script base name.</summary>
   private static readonly Regex s_deployerSuffix =
      new Regex(@"@\d+(?:\.public)?$", RegexOptions.IgnoreCase);

   /// <summary>
   /// Strips the namespace prefix from a fully-qualified type name so that unqualified
   /// annotations (<c>@return TagSummary</c>) can match against fully-qualified registrations
   /// (<c>[JsonSerializable(typeof(BlazorWebApp.TagSummary))]</c>).
   /// Handles simple arrays: <c>"My.Ns.Foo[]"</c> → <c>"Foo[]"</c>.
   /// </summary>
   private static string GetSimpleName(string fullTypeName)
   {
      // Handle generics: Namespace.Outer<Namespace.Inner> → Outer<Inner>
      var genericOpen = fullTypeName.IndexOf('<');
      if (genericOpen >= 0 && fullTypeName.EndsWith(">"))
      {
         var outer = fullTypeName.Substring(0, genericOpen);
         var inner = fullTypeName.Substring(genericOpen + 1, fullTypeName.Length - genericOpen - 2);
         return $"{StripNamespace(outer)}<{GetSimpleName(inner)}>";
      }
      // Handle arrays: Namespace.T[] → T[]
      if (fullTypeName.EndsWith("[]"))
         return GetSimpleName(fullTypeName.Substring(0, fullTypeName.Length - 2)) + "[]";
      return StripNamespace(fullTypeName);
   }

   private static string StripNamespace(string typeName)
   {
      var dot = typeName.LastIndexOf('.');
      return dot >= 0 ? typeName.Substring(dot + 1) : typeName;
   }

   /// <summary>
   /// Returns true when we must verify [JsonSerializable] is present.
   /// Primitive C# types are always resolvable from any JsonSerializerContext
   /// without explicit registration.
   /// </summary>
   private static bool NeedsJsonSerializableCheck(string csType) =>
      csType != "string"
      && csType != "double"
      && csType != "float"
      && csType != "bool"
      && csType != "int"
      && csType != "long"
      && csType != "short"
      && csType != "byte"
      && csType != "char"
      && csType != "decimal";

   private static string SanitizeHintName(string name)
   {
      var sb = new StringBuilder(name.Length);
      foreach (var c in name)
         sb.Append(char.IsLetterOrDigit(c) || c == '_' || c == '-' ? c : '_');
      return sb.ToString();
   }

   private static void ReportSemanticDiagnostics(
      SourceProductionContext spc,
      AdditionalText          file,
      SourceText              text,
      string                  source)
   {
      // Parse and analyse
      var parseResult = CgScriptParseService.Parse(source);
      var allDiags    = new List<Parsing.Diagnostic>(parseResult.Diagnostics);

      var semanticDiags = SemanticAnalyzer.Analyze(
         parseResult.Tree,
         KnownNamesLoader.FunctionNames,
         KnownNamesLoader.ObjectNames,
         KnownNamesLoader.ConstantNames);

      allDiags.AddRange(semanticDiags);

      foreach (var d in allDiags)
      {
         var descriptor = CgScriptDiagnostics.DescriptorFor(d);
         var location   = ToLocation(file, text, d);
         spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(descriptor, location, d.Message));
      }
   }

   private static Location ToLocation(AdditionalText file, SourceText text, Parsing.Diagnostic d)
   {
      if (d.Line <= 0 || d.Line > text.Lines.Count)
         return Location.None;

      var line = text.Lines[d.Line - 1];
      var col  = System.Math.Min(d.Column, line.Span.Length);
      var len  = System.Math.Min(d.Length, line.Span.Length - col);
      var span = new TextSpan(line.Start + col, System.Math.Max(len, 0));
      return Location.Create(file.Path, span, text.Lines.GetLinePositionSpan(span));
   }
}
