using System.Text;

namespace Catglobe.CgScript.EditorSupport.SourceGenerator;

/// <summary>
/// Emits C# source for a typed AOT-safe wrapper method for one .cgs script.
///
/// Both the Params and return-type <c>JsonTypeInfo</c> are resolved from the assembly's
/// <c>[CgScriptSerializer]</c> context. The generator also emits a partial declaration of
/// that context class with the required <c>[JsonSerializable]</c> attribute for every
/// generated Params type, so users never need to add them manually.
/// </summary>
internal static class WrapperEmitter
{
   /// <summary>
   /// Generates the partial class body (without namespace/class wrapper) for one script.
   /// </summary>
   public static string Emit(ScriptMetadata meta, string wrapperNamespace, string contextFullName)
   {
      var sb = new StringBuilder();

      var lastSlash   = meta.ScriptName.LastIndexOf('/');
      var methodName  = ToPascalCase(lastSlash >= 0
                           ? meta.ScriptName.Substring(lastSlash + 1)
                           : meta.ScriptName);
      var paramsClass = methodName + "Params";
      var isVoid      = meta.ReturnType == "void";
      var returnCs    = isVoid ? "object" : meta.ReturnType;

      // ── XML doc comment ──────────────────────────────────────────────────────
      sb.AppendLine($"    // Generated from {meta.ScriptName}.cgs");
      sb.AppendLine("    /// <summary>");
      sb.AppendLine($"    /// {XmlEscape(meta.Summary ?? $"Calls the <c>{meta.ScriptName}</c> CgScript.")}");
      sb.AppendLine("    /// </summary>");
      foreach (var p in meta.Parameters)
      {
         if (p.Doc != null)
            sb.AppendLine($"    /// <param name=\"{ToCamelCase(p.Name)}\">{XmlEscape(p.Doc)}</param>");
      }
      if (meta.ReturnDoc != null)
         sb.AppendLine($"    /// <returns>{XmlEscape(meta.ReturnDoc)}</returns>");
      if (isVoid)
         sb.Append($"    public static async global::System.Threading.Tasks.Task {methodName}(");
      else
         sb.Append($"    public static async global::System.Threading.Tasks.Task<{returnCs}> {methodName}(");
      sb.Append("this global::Catglobe.CgScript.Runtime.ICgScriptApiClient client");
      foreach (var p in meta.Parameters)
      {
         if (p.IsOptional)
            sb.Append($", {MakeNullable(p.CsType)} {ToCamelCase(p.Name)} = null");
         else
            sb.Append($", {p.CsType} {ToCamelCase(p.Name)}");
      }
      sb.AppendLine(", global::System.Threading.CancellationToken ct = default)");
      sb.AppendLine("    {");
      sb.AppendLine($"        var ctx = global::{contextFullName}.Default;");

      // Both params and result are resolved from the source-generated context — fully AOT-safe.
      sb.AppendLine($"        var paramsInfo = ctx.{paramsClass};");
      sb.AppendLine($"        var resultInfo = ctx.{ToStjPropertyName(returnCs)};");

      var executeExpr = $"client.Execute<{paramsClass}, {returnCs}>(\"{meta.ScriptName}\", new {paramsClass}({string.Join(", ", meta.Parameters.Select(p => ToCamelCase(p.Name)))}), paramsInfo, resultInfo, cancellationToken: ct)";
      if (isVoid)
         sb.AppendLine($"        (await {executeExpr}).GetValueOrThrowError();");
      else
         sb.AppendLine($"        return (await {executeExpr}).GetValueOrThrowError();");

      sb.AppendLine("    }");
      sb.AppendLine();

      // ── params record ────────────────────────────────────────────────────────
      // internal (not private) so [JsonSerializable(typeof(...))] in the auto-generated
      // partial context class can reference it.
      // [property: JsonPropertyName] preserves the original camelCase JSON key names.
      sb.Append($"    internal record {paramsClass}(");
      sb.Append(string.Join(", ", meta.Parameters.Select(p =>
      {
         var attr      = $"[property: global::System.Text.Json.Serialization.JsonPropertyName(\"{p.Name}\")]";
         var csType    = p.IsOptional ? MakeNullable(p.CsType) : p.CsType;
         var defaultVal = p.IsOptional ? " = null" : "";
         return $"{attr} {csType} {ToPascalCase(p.Name)}{defaultVal}";
      })));
      sb.AppendLine(");");

      return sb.ToString();
   }

   /// <summary>
   /// Wraps all emitted methods in a single partial class file.
   /// </summary>
   public static string WrapInPartialClass(string wrapperNamespace, string body)
   {
      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated />");
      sb.AppendLine("#nullable enable");
      sb.AppendLine();
      sb.AppendLine($"namespace {wrapperNamespace}");
      sb.AppendLine("{");
      sb.AppendLine("    public static partial class CgScriptExtensions");
      sb.AppendLine("    {");
      sb.AppendLine(body);
      sb.AppendLine("    }");
      sb.AppendLine("}");
      return sb.ToString();
   }

   private static string MakeNullable(string csType)
   {
      if (csType.EndsWith("?")) return csType;
      return csType + "?";
   }

   /// <summary>
   /// Converts a C# type name to the property name generated by the STJ source generator on a
   /// <see cref="System.Text.Json.Serialization.JsonSerializerContext"/>.
   /// e.g. "IEnumerable&lt;TagItem&gt;" → "IEnumerableTagItem", "string" → "String"
   /// </summary>
   internal static string ToStjPropertyName(string csType)
   {
      // Nullable value types: "T?" → "NullableT" (e.g. "int?" → "NullableInt32")
      if (csType.EndsWith("?"))
         return "Nullable" + ToStjPropertyName(csType.Substring(0, csType.Length - 1));

      // C# keyword aliases → CLR names used by STJ
      switch (csType)
      {
         case "string":  return "String";
         case "bool":    return "Boolean";
         case "int":     return "Int32";
         case "double":  return "Double";
         case "float":   return "Single";
         case "long":    return "Int64";
         case "short":   return "Int16";
         case "byte":    return "Byte";
         case "object":  return "Object";
      }

      // Generic type: "Outer<Inner>" → "Outer" + ToStjPropertyName("Inner")
      var lt = csType.IndexOf('<');
      if (lt >= 0 && csType[csType.Length - 1] == '>')
      {
         var outerRaw  = csType.Substring(0, lt);
         var dot       = outerRaw.LastIndexOf('.');
         var outerName = dot >= 0 ? outerRaw.Substring(dot + 1) : outerRaw;
         var innerType = csType.Substring(lt + 1, csType.Length - lt - 2);
         return outerName + ToStjPropertyName(innerType);
      }

      // Simple user-defined type — strip any namespace prefix
      var lastDot = csType.LastIndexOf('.');
      return lastDot >= 0 ? csType.Substring(lastDot + 1) : csType;
   }

   // ── helpers ──────────────────────────────────────────────────────────────────

   internal static string ToPascalCase(string s)
   {
      if (string.IsNullOrEmpty(s)) return s;
      var sb = new StringBuilder(s.Length);
      bool capitalize = true;
      foreach (var c in s)
      {
         if (char.IsLetterOrDigit(c) || c == '_')
         {
            sb.Append(capitalize && char.IsLetter(c) ? char.ToUpperInvariant(c) : c);
            capitalize = false;
         }
         else
         {
            capitalize = true; // capitalize next valid char after separator
         }
      }
      if (sb.Length > 0 && char.IsDigit(sb[0]))
         sb.Insert(0, '_');
      return sb.Length > 0 ? sb.ToString() : "_";
   }

   private static string ToCamelCase(string s)
   {
      if (string.IsNullOrEmpty(s)) return s;
      return char.ToLowerInvariant(s[0]) + s.Substring(1);
   }

   private static string XmlEscape(string s) =>
      s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}

