using System.Text;

namespace Catglobe.CgScript.EditorSupport.SourceGenerator;

/// <summary>
/// Emits C# source for a typed wrapper method and supporting types for one .cgs script.
/// </summary>
internal static class WrapperEmitter
{
   /// <summary>
   /// Generates the partial class body (without namespace/class wrapper) for one script.
   /// </summary>
   public static string Emit(ScriptMetadata meta, string wrapperNamespace)
   {
      var sb = new StringBuilder();

      var methodName  = ToPascalCase(meta.ScriptName);
      var paramsClass = methodName + "Params";
      var returnCs    = meta.ReturnType == "void" ? "object" : meta.ReturnType;

      // ── extension method ─────────────────────────────────────────────────────
      sb.AppendLine($"    // Generated from {meta.ScriptName}.cgs");
      sb.Append($"    public static global::System.Threading.Tasks.Task<global::Catglobe.CgScript.Runtime.ScriptResult<{returnCs}>> {methodName}(");
      sb.Append("this global::Catglobe.CgScript.Runtime.ICgScriptApiClient client");

      foreach (var p in meta.Parameters)
         sb.Append($", {CsType(p)} {ToCamelCase(p.Name)}");

      sb.AppendLine(", global::System.Threading.CancellationToken ct = default)");
      sb.AppendLine("    {");
      // The params record is emitted by this source generator and is therefore invisible
      // to the System.Text.Json source generator (generators cannot see each other's output).
      // Reflection-based serialization is used; it is safe for server-side scenarios.
#pragma warning disable RS1035 // Do not use APIs banned for use in analyzers
      sb.AppendLine("#pragma warning disable IL2026, IL3050");
#pragma warning restore RS1035
      sb.Append($"        return client.Execute<{paramsClass}, {returnCs}>(");
      sb.Append($"\"{meta.ScriptName}\", ");
      sb.Append($"new {paramsClass}(");
      sb.Append(string.Join(", ", meta.Parameters.Select(p => ToCamelCase(p.Name))));
      sb.AppendLine("), cancellationToken: ct);");
#pragma warning disable RS1035
      sb.AppendLine("#pragma warning restore IL2026, IL3050");
#pragma warning restore RS1035
      sb.AppendLine("    }");
      sb.AppendLine();

      // ── params record ────────────────────────────────────────────────────────
      if (meta.Parameters.Count > 0)
      {
         sb.Append($"    private record {paramsClass}(");
         sb.Append(string.Join(", ", meta.Parameters.Select(p => $"{CsType(p)} {ToPascalCase(p.Name)}")));
         sb.AppendLine(");");
      }
      else
      {
         sb.AppendLine($"    private record {paramsClass}();");
      }

      return sb.ToString();
   }

   /// <summary>
   /// Wraps all emitted methods in a single partial class file.
   /// </summary>
   public static string WrapInPartialClass(string wrapperNamespace, string body)
   {
      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated />");
      sb.AppendLine("#nullable enable");
      sb.AppendLine();
      sb.AppendLine($"namespace {wrapperNamespace}");
      sb.AppendLine("{");
      sb.AppendLine("    public static partial class CgScriptWrappers");
      sb.AppendLine("    {");
      sb.AppendLine(body);
      sb.AppendLine("    }");
      sb.AppendLine("}");
      return sb.ToString();
   }

   private static string CsType(ScriptParam p) => ScriptParser.ToCsType(p.CgsType);

   // ── helpers ──────────────────────────────────────────────────────────────────

   internal static string ToPascalCase(string s)
   {
      if (string.IsNullOrEmpty(s)) return s;
      var sb = new StringBuilder(s.Length);
      bool capitalize = true;
      foreach (var c in s)
      {
         if (char.IsLetterOrDigit(c) || c == '_')
         {
            sb.Append(capitalize && char.IsLetter(c) ? char.ToUpperInvariant(c) : c);
            capitalize = false;
         }
         else
         {
            capitalize = true; // capitalize next valid char after a separator
         }
      }
      // Ensure it doesn't start with a digit
      if (sb.Length > 0 && char.IsDigit(sb[0]))
         sb.Insert(0, '_');
      return sb.Length > 0 ? sb.ToString() : "_";
   }

   private static string ToCamelCase(string s)
   {
      if (string.IsNullOrEmpty(s)) return s;
      return char.ToLowerInvariant(s[0]) + s.Substring(1);
   }
}
