using System.Text;

namespace Catglobe.CgScript.EditorSupport.SourceGenerator;

/// <summary>
/// Emits C# source for a typed wrapper method and supporting types for one .cgs script.
/// </summary>
internal static class WrapperEmitter
{
   /// <summary>
   /// Generates the partial class body (without namespace/class wrapper) for one script.
   /// </summary>
   public static string Emit(ScriptMetadata meta, string wrapperNamespace)
   {
      var sb = new StringBuilder();

      var methodName  = ToPascalCase(meta.ScriptName);
      var paramsClass = methodName + "Params";
      var ctxClass    = methodName + "Context";
      var returnCs    = meta.ReturnType;

      // ── extension method ─────────────────────────────────────────────────────
      sb.AppendLine($"    // Generated from {meta.ScriptName}.cgs");
      sb.Append($"    public static global::System.Threading.Tasks.Task<global::Catglobe.CgScript.Common.ScriptResult<{returnCs}>> {methodName}(");
      sb.Append("this global::Catglobe.CgScript.Common.ICgScriptApiClient client");

      foreach (var p in meta.Parameters)
         sb.Append($", {CsType(p)} {ToCamelCase(p.Name)}");

      sb.AppendLine(", global::System.Threading.CancellationToken ct = default)");
      sb.AppendLine("    {");
      sb.Append($"        return client.Execute<{paramsClass}, {returnCs}>(");
      sb.Append($"\"{meta.ScriptName}\", ");
      sb.Append($"new {paramsClass}(");
      sb.Append(string.Join(", ", meta.Parameters.Select(p => ToCamelCase(p.Name))));
      sb.Append("), ");
      sb.Append($"{ctxClass}.Default.{paramsClass}, ");
      sb.Append($"{ctxClass}.Default.{CsContextReturnType(returnCs)}, ");
      sb.AppendLine("ct);");      sb.AppendLine("    }");
      sb.AppendLine();

      // ── params record ────────────────────────────────────────────────────────
      if (meta.Parameters.Count > 0)
      {
         sb.Append($"    private record {paramsClass}(");
         sb.Append(string.Join(", ", meta.Parameters.Select(p => $"{CsType(p)} {ToPascalCase(p.Name)}")));
         sb.AppendLine(");");
      }
      else
      {
         sb.AppendLine($"    private record {paramsClass}();");
      }
      sb.AppendLine();

      // ── JsonSerializerContext ─────────────────────────────────────────────────
      sb.AppendLine($"    [global::System.Text.Json.Serialization.JsonSerializable(typeof({paramsClass}))]");
      if (returnCs != "void")
         sb.AppendLine($"    [global::System.Text.Json.Serialization.JsonSerializable(typeof({returnCs}))]");
      sb.AppendLine($"    private partial class {ctxClass} : global::System.Text.Json.Serialization.JsonSerializerContext {{}}");

      return sb.ToString();
   }

   /// <summary>
   /// Wraps all emitted methods in a single partial class file.
   /// </summary>
   public static string WrapInPartialClass(string wrapperNamespace, string body)
   {
      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated />");
      sb.AppendLine("#nullable enable");
      sb.AppendLine();
      sb.AppendLine($"namespace {wrapperNamespace}");
      sb.AppendLine("{");
      sb.AppendLine("    public static partial class CgScriptWrappers");
      sb.AppendLine("    {");
      sb.AppendLine(body);
      sb.AppendLine("    }");
      sb.AppendLine("}");
      return sb.ToString();
   }

   private static string CsType(ScriptParam p) => ScriptParser.ToCsType(p.CgsType);

   // ── helpers ──────────────────────────────────────────────────────────────────

   private static string ToPascalCase(string s)
   {
      if (string.IsNullOrEmpty(s)) return s;
      return char.ToUpperInvariant(s[0]) + s.Substring(1);
   }

   private static string ToCamelCase(string s)
   {
      if (string.IsNullOrEmpty(s)) return s;
      return char.ToLowerInvariant(s[0]) + s.Substring(1);
   }

   private static string CsContextReturnType(string returnCs) => returnCs switch
   {
      "void"     => "Object",
      "int"      => "Int32",
      "double"   => "Double",
      "bool"     => "Boolean",
      "string"   => "String",
      "object[]" => "ObjectArray",
      _          => ToPascalCase(returnCs),
   };
}
