name: Release Catglobe.ScriptDeployer NuPkg
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - next

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup .NET
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
        with:
          dotnet-version: '10'
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          cache: npm
          cache-dependency-path: |
            package-lock.json
            Catglobe.CgScript.EditorSupport.CodeMirror.AspNet/package-lock.json
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm clean-install
      - name: Test
        run: dotnet test
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: nuget
        with:
          user: Catglobe
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{steps.nuget.outputs.NUGET_API_KEY}}

